// == Exceptions
:solution:

### Frage
Wenn eine Exception geworfen wird, dann sieht sich Java zur Laufzeit außerstande ...?

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]

### Frage
[question,mc]
====
Kann `javac`, der Java-Compiler, eine Exception zu Ihrem Code werfen?

- [x] Ginge es in der Frage um `java` statt `javac`, dann wäre die Antwort "Ja"
- [x] Nein, der Compiler kann nur den Ausnahmecode generieren aber nicht Ausnahmen werfen
- [ ] Ja, denn Exceptions sind ein Compiler-Konstrukt, sie stehen ja im Programmcode
- [x] Nein, Exceptions sind ein Laufzeit-Konstrukt, der Compiler hat damit nichts zu tun
====

### Frage
[question,mc]
====
Die Informationen, die zu einer Exception geführt haben, werden wie kommuniziert?

- [ ] Über eine Ausgabe mittels `System.out.println`
- [ ] Es wird eine Klasse aus der Klassenhierarchie für Ausnahmen übergeben
- [ ] Über einen String ohne Ausgabe mittels `System.out.println`
- [x] Es wird eine Instanz aus der Klassenhierarchie für Ausnahmen übergeben
====

### Frage
[question,mc]
====
Wie heißt die oberste Klasse in der Exception-Hierarchie?

- [ ] `Exception`
- [ ] `RuntimeException`
- [x] `Throwable`
- [ ] `Error`
====

### Frage
Was ist ein _Stack Trace_?

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]

### Frage
Wenn eine Exception vom Typ `Error` geworfen wird, dann hat das was für Konsequenzen?

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]

### Frage
Was unterscheidet Exceptions, die von `RuntimeException` erben von anderen Subklassen von `Exception`?

ifdef::solution[]
.Antwort
`RuntimeExceptions` dürfen mit `try/catch` abgefangen werden, aber sie müssen nicht. Andere ('normale') Exceptions müssen hingegen abgefangen werden, oder die betreffende Methode muss selbst mit `throws` deklariert werden, so dass diese die Exception weitergibt.
endif::solution[]

### Frage
Warum ist der Name `RuntimeException` für eine der Exception-Klassen ein wenig unsinnig?

ifdef::solution[]
.Antwort
Der Begriff _Runtime_ ist deswegen unglücklich, weil ja _alle_ Exceptions zur Laufzeit auftreten. _Runtime_-Exceptions in Java zeichnen sich vielmehr dadurch aus, dass sie praktisch ausnahmslos auf Schlampigkeitsfehler des Programmiers bzw. der Programmiererin zurückzuführen sind. Anders formuliert: Wenn Sie ordentlich programmieren, sollten keine _Runtime_-Exceptions auftreten. Auf andere Exceptions haben Sie hingegen oft keinen Einfluss; diese können durch 'höhere Gewalt' außerhalb des Java-Programms auftreten (z.B. wenn eine Netzwerkverbindung plötzlich nicht mehr besteht, weil jemand das Kabel gelöst hat).
endif::solution[]

### Frage
In welchem Fall muss im Kopf einer Methode `throws` samt Angabe der möglichen Ausnahme(n) stehen?

ifdef::solution[]
.Antwort
Wenn innerhalb der Methode eine entsprechende Exception ohne `try/catch`-Absicherung ausgelöst werden kann, sei es direkt durch den Aufruf von `throw`, sei es durch den Aufruf einer anderen Methode, die mit `throws` deklariert ist.
endif::solution[]

### Frage
Wenn `catch`-Blöcke identischen Code haben, bietet sich eine Verkürzungsform an. Beschreiben Sie den syntaktischen Aufbau des "verkürzten" `catch`-Kopfes.

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]

### Frage
Die StackTrace eines `StackOverflowError` ist sehr lang. Warum?

ifdef::solution[]
.Antwort
Der Fehler tritt auf, wenn der Stack voll ist, was in der Regel erst dann passiert, wenn sehr viele (oft Millionen) Methoden einander aufgerufen haben.
endif::solution[]

### Frage
`try { /* some code */ }` and there is something wrong.

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]

### Frage
Was ist der Vorteil eines _try-with-resources_ gegenüber einem normalen `finally`-Block?

ifdef::solution[]
.Antwort
Übersichtlicherer Code.
endif::solution[]

### Frage
Anschlussfrage: Was ist eine _resource_?

ifdef::solution[]
.Antwort
Ein Objekt einer Klasse, die die Schnittstelle `AutoClosable` definiert. Siehe <https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html>.
endif::solution[]

### Frage
Ein Student schreibt folgende main-Methode und wird sofort dafür gescholten. Warum?
[source,java]
----
public static void main(String[] args) throws Throwable {
  // ...
}
----

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]


### Frage
Was macht die `assert`-Anweisung?

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]

### Frage
[source,java]
----
try {
  // dangerous stuff
} catch (Exception e) {
  e.printStackTrace();
} catch (NumberFormatException nfe) {
  System.err.println("Stupid user input!")
}
----
Geht das?

ifdef::solution[]
.Antwort
Jeder Fehler wird von der ersten `catch`-Anweisung abgefangen, auch die `NumberFormatException`. Daher kann es nie zum Aufruf des zweiten `catch`-Blocks kommen.
endif::solution[]

### Frage
Sie haben in Ihrem Code `assert`-Anweisungen, die eigentlich eine Exception auslösen müssten (Beispiel: `assert false;`). Die Exceptions bleiben aus. Was ist los?

ifdef::solution[]
.Antwort
-- TODO --
endif::solution[]

### Frage
Kann man selbst Exceptions definieren?

ifdef::solution[]
.Antwort
Ja. Sie müssen Ihre eigene Exception-Klasse einfach von `Exception` bzw. von `ExceptionXy` ableiten.
endif::solution[]
